import { useLanguage } from "../../../context/LanguageContext";

export default function BillPrint({ bill }) {
  const { t, language } = useLanguage();

  if (!bill) {
    return null;
  }

  const items = bill.items || [];

  if (items.length === 0) {
    return null;
  }

  const today = new Date(
    bill.createdAt || Date.now()
  ).toLocaleDateString("en-IN");

  const getLocalizedProductName = (item) => {
    if (!item) {
      return "";
    }

    if (language === "hi") {
      return (
        item.nameHi ||
        item.nameEn ||
        ""
      );
    }

    return (
      item.nameEn ||
      item.nameHi ||
      ""
    );
  };

  const getLocalizedUnitName = (item) => {
    if (!item) {
      return "";
    }

    let unitName =
      language === "hi"
        ? item.unitNameHi ||
          item.unitNameEn ||
          ""
        : item.unitNameEn ||
          item.unitNameHi ||
          "";

    if (!unitName) {
      return "";
    }

    if (item.unitShortName) {
      return `${unitName} (${item.unitShortName})`;
    }

    return unitName;
  };

  return (
    <div className="print-only print-page">
      <div className="print-container">
        {/* ================================
            HEADER
        ================================= */}

        {/* Row 1: Date / Bill Number / Generated By */}
        <div className="print-header-row">
          <div className="print-date">
            {t("date")}: {today}
          </div>

          <div className="print-bill-number">
            {t("billNumber")}:{" "}
            {bill.billNumber}
          </div>

          <div className="print-generated-by">
            {t("generatedBy")}:{" "}
            {bill.generatedBy?.name || "-"}
          </div>
        </div>

        {/* Row 2: Customer / Form */}
        <div className="print-customer-row">
          <span className="print-customer-label">
            {t("customerForm")}:
          </span>

          <span className="customer-line"></span>
        </div>

        {/* ================================
            ITEMS TABLE
        ================================= */}

        <table className="print-table">
          <thead>
            <tr>
              <th className="serial-column">
                {t("serialNumber")}
              </th>

              <th className="item-column">
                {t("item")}
              </th>

              <th className="quantity-column">
                {t("qty")}
              </th>

              <th className="unit-column">
                {t("unit")}
              </th>

              <th className="rate-column">
                {t("rate")}
              </th>

              <th className="price-column">
                {t("price")}
              </th>
            </tr>
          </thead>

          <tbody>
            {items.map((item, index) => {
              const productName =
                getLocalizedProductName(item);

              const unitName =
                getLocalizedUnitName(item) || "-";

              const qty =
                item.quantity !== undefined &&
                item.quantity !== null
                  ? item.quantity
                  : "";

              const hasRate =
                item.rate !== "" &&
                item.rate !== null &&
                item.rate !== undefined &&
                !Number.isNaN(
                  Number(item.rate)
                );

              const rate = hasRate
                ? Number(item.rate)
                : null;

              const numericQty =
                Number(qty);

              const price =
                rate !== null &&
                Number.isFinite(numericQty)
                  ? numericQty * rate
                  : null;

              return (
                <tr
                  key={
                    item.productId ??
                    index
                  }
                >
                  {/* Serial Number */}
                  <td className="text-center">
                    {index + 1}
                  </td>

                  {/* Product */}
                  <td>
                    {productName}

                    {item.brand && (
                      <span className="print-brand">
                        {" "}
                        — {item.brand}
                      </span>
                    )}
                  </td>

                  {/* Quantity */}
                  <td className="text-center">
                    {qty}
                  </td>

                  {/* Unit */}
                  <td className="text-center">
                    {unitName}
                  </td>

                  {/* Rate */}
                  <td className="text-right">
                    {rate !== null
                      ? `₹${rate.toLocaleString(
                          "en-IN",
                          {
                            minimumFractionDigits: 2,
                            maximumFractionDigits: 2,
                          }
                        )}`
                      : ""}
                  </td>

                  {/* Price */}
                  <td className="text-right">
                    {price !== null
                      ? `₹${price.toLocaleString(
                          "en-IN",
                          {
                            minimumFractionDigits: 2,
                            maximumFractionDigits: 2,
                          }
                        )}`
                      : ""}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>

        {/* ================================
            TOTAL
        ================================= */}

        <div className="print-total">
          <span>
            {t("total")}:
          </span>

          <span className="print-total-value">
            {bill.total !== null &&
            bill.total !== undefined
              ? `₹${Number(
                  bill.total
                ).toLocaleString(
                  "en-IN",
                  {
                    minimumFractionDigits: 2,
                    maximumFractionDigits: 2,
                  }
                )}`
              : ""}
          </span>
        </div>
      </div>
    </div>
  );
}